version: '3'

networks:
    network1:

services:

    # nginx
    nginx-service-yii:
        image: nginx:stable-alpine
        container_name: nginx-container-yii
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service-yii
            - postgres133-service-yii
        networks:
            - network1

    # php
    php74-service-yii:
        restart: always
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container-yii
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - network1

    # postgres
    postgres133-service-yii:
        image: postgres:13.3
        container_name: postgres133-container-yii
        ports:
            - "5432:5432"
        restart: always # always restart unless stopped manually
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        networks:
            - network1



